version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  fastapi:
    build: ./fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: ./celery_worker
    depends_on:
      - redis